var dlib_header = "<?xml version='1.0' encoding='ISO-8859-1'?>\n"
    +"<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>\n"
    +"<dataset>\n"
    +"<name>dlib face detection dataset generated by ImgLab</name>\n"
    +"<comment>\n"
    +"   This dataset is manually crafted or adjusted using ImgLab web tool\n"
    +"   Check more detail on https://github.com/NaturalIntelligence/imglab\n"
    +"</comment>\n"
    +"<images>\n"

/*var dlib_data = "  <image file='#FILENAME#'>"
    
               +"  </image>"
var dlib_box_data = +"    <box top='130' left='129' width='92' height='91'/>"*/
var dlib_footer = "</images>"
             +"</dataset>"
function toDlib(imgs){
    var imgXMLStr = "";
    for(var img in imgs){
        imgXMLStr += "\t<image file='"+ imgs[img].name+"'>\n";
        var boxes = imgs[img].boxes;
        if(boxes){
            for(var box in boxes){
                var l = boxes[box].left, t = boxes[box].top;
                imgXMLStr += "\t\t<box top='"+t+"' left='"+l+"' width='"+boxes[box].width+"' height='"+boxes[box].height+"'>\n";
                imgXMLStr += "\t\t\t<label>"+box+"</label>\n";
                //Add points information
                var points = boxes[box].points;
                for(var point in points){
                    imgXMLStr += "\t\t\t<part name='"+points[point].label+"' x='"+(points[point].x+l)+"' y='"+(points[point].y+t)+"'/>\n";
                }
                imgXMLStr += "\t\t</box>\n"
            }
        }
        imgXMLStr += "\t</image>\n";
    }

    return dlib_header + imgXMLStr + dlib_footer;
}

/*PTS file contains landmark points in an image file */
function toDlibPts(boxEl){
    var data = "version: 1\n"
            +"n_points:  "+boxEl.children().length+"\n"
            +"{\n";
    var l = boxEl.position().left, t = boxEl.position().top;
    boxEl.children().each(function(){
        data += ($(this).position().left + l ) + " " + ($(this).position().top + t) + "\n";
    });

    data += "}";

    return data;
}