var dlib_header = "<?xml version='1.0' encoding='ISO-8859-1'?>"
    +"<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>"
    +"<dataset>"
    +"<name>dlib face detection dataset generated by ImgLab</name>"
    +"<comment>"
    +"   This dataset is manually crafted or adjusted using ImgLab web tool"
    +"   Check more detail on https://github.com/NaturalIntelligence/imglab"
    +"</comment>\n";

/*var dlib_data = "  <image file='#FILENAME#'>"
    
               +"  </image>"
var dlib_box_data = +"    <box top='130' left='129' width='92' height='91'/>"*/
var dlib_footer = "</images>"
             +"</dataset>"
function toDlib(imgs){
    var imgXMLStr = "";
    for(var img in imgs){
        imgXMLStr += "<image file='"+ imgs[img].name+"'>\n";
        var boxes = imgs[img].boxes;
        if(boxes){
            for(var box in boxes){
                imgXMLStr += "<box top='"+boxes[box].top+"' left='"+boxes[box].left+"' width='"+boxes[box].width+"' height='"+boxes[box].height+"'>\n";
                imgXMLStr += "<label>"+box+"</label>\n";
                imgXMLStr += "</box>\n"
            }
        }
        imgXMLStr += "</image>\n";
    }

    return dlib_header + imgXMLStr + dlib_footer;
}

/*PTS file contains landmark points in an image file */
function toDlibPts(boxEl){
    var data = "version: 1\n"
            +"n_points:  "+boxEl.children().length+"\n"
            +"{\n";
    boxEl.children().each(function(){
        data += $(this).position().left + " " + $(this).position().top + "\n";
    });

    data += "}";

    return data;
}