var dlib_header = "<?xml version='1.0' encoding='ISO-8859-1'?>\n"
    +"<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>\n"
    +"<dataset>\n"
    +"<name>dlib face detection dataset generated by ImgLab</name>\n"
    +"<comment>\n"
    +"   This dataset is manually crafted or adjusted using ImgLab web tool\n"
    +"   Check more detail on https://github.com/NaturalIntelligence/imglab\n"
    +"</comment>\n"
    +"<images>\n"

/*var dlib_data = "  <image file='#FILENAME#'>"
    
               +"  </image>"
var dlib_box_data = +"    <box top='130' left='129' width='92' height='91'/>"*/
var dlib_footer = "</images>"
             +"</dataset>";

//create face data xml file for dlib
//face data xml file can have data for multiple images
//for each image there can be multiple labelled box
//each labelled box can have multiple feature points called parts
function toDlibXML(imgs){
    var imgXMLStr = "";
    var img_keys = Object.keys(imgs);
    for(var img_i in img_keys){
        var imgName = img_keys[ img_i] ;
        var img = imgs [ imgName ];
        imgXMLStr += "\t<image file='"+ imgName +"'>\n";
        var shapes = img.shapes;
        //if(boxes){
            var shapeIds = Object.keys(shapes);
            for(var shape_i in shapeIds){
                var shapeId = shapeIds[ shape_i ];
                var shapeLabel = shapes [ shapeId ].label;
                var box = shapes [ shapeId ].bbox;
                imgXMLStr += "\t\t<box top='"+box.y+"' left='"+box.x+"' width='"+box.width+"' height='"+box.height+"'>\n";
                imgXMLStr += "\t\t\t<label>"+ shapeLabel +"</label>\n";
                //Add points information
                var fPoints = shapes [ shapeId ].featurePoints;
                //if(fPoints){
                    var fp_keys = Object.keys(fPoints);
                    for(var fPoint_i in fp_keys){
                        var fPointId = fp_keys[ fPoint_i ];
                        var fPoint = fPoints [ fPointId ];
                        imgXMLStr += "\t\t\t<part name='"+ fPoint.label +"' x='"+ fPoint.x+"' y='"+ fPoint.y +"'/>\n";
                    }
                //}
                imgXMLStr += "\t\t</box>\n"
            }
        //}
        imgXMLStr += "\t</image>\n";
    }

    return dlib_header + imgXMLStr + dlib_footer;
}

/*PTS file contains landmark points location without label and of single label box only  */
function toDlibPts(shape){
    var keys = Object.keys(shape.featurePoints);
    var data = "version: 1\n"
            +"n_points:  "+keys.length+"\n"
            +"{\n";
    var l = shape.bbox.x, t = shape.bbox.y;
    keys.forEach( fp_id => {
        data += shape.featurePoints[ fp_id ].x + " " + shape.featurePoints[ fp_id ].y + "\n";
    });

    data += "}";

    return data;
}